apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app
  namespace: nodejs
  labels:
    app: node-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-app
  template:
    metadata:
      labels:
        app: node-js-app
    spec:
      containers:
      - name: node-js-app
        image: docker.io/in3t/node-js-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: APP_VERSION
          value: "v1.0.0"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
