apiVersion: v1
kind: Service
metadata:
  name: node-js-app
  namespace: nodejs
  labels:
    app: node-js-app
spec:
  type: ClusterIP
  selector:
    app: node-js-app
  ports:
  - name: http
    port: 80
    targetPort: http
