apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-argocd-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_WITH_YOUR_GITHUB_USER/REPLACE_WITH_YOUR_REPOSITORY.git
    targetRevision: main
    path: nodejs-argocd-sample/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
