apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-argocd-sample
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/in3t3/nodejs-argocd-sample.git
    targetRevision: main
    path: nodejs-argocd-sample/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
